name: Update Parks Data

on: [workflow_dispatch]

jobs:
  daily-update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Update park data
        run: yarn update

      - name: Commit updated data
        run: |-
          git config user.name "ParkBot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "`date +'%Y-%m-%d'` updated park data" || exit 0
          git push

      - name: Generate boundaries
        run: yarn generate-boundaries

      - name: Commit updated boundaries
        run: |-
          git config user.name "ParkBot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "`date +'%Y-%m-%d'` updated park boundaries" || exit 0
          git push
